import './page/lieferzeiten-management-page';

Shopware.Module.register('lieferzeiten-management', {
    type: 'plugin',
    name: 'lieferzeiten-management',
    title: 'lieferzeiten-management.general.mainMenuItemGeneral',
    description: 'lieferzeiten-management.general.descriptionTextModule',
    color: '#1a73e8',
    icon: 'regular-clock',
    routes: {
        index: {
            component: 'lieferzeiten-management-page',
            path: 'index',
        },
    },
    navigation: [
        {
            id: 'lieferzeiten-management',
            label: 'lieferzeiten-management.general.mainMenuItemGeneral',
            path: 'lieferzeiten.management.index',
            parent: 'sw-order',
            position: 110,
        },
    ],
});

Shopware.Locale.extend('en-GB', {
    'lieferzeiten-management': {
        general: {
            mainMenuItemGeneral: 'Delivery times',
            descriptionTextModule: 'Manage delivery times and tracking',
            title: 'Delivery times',
            filtersTitle: 'Filters',
            filterTracking: 'Tracking number',
            filterPackageStatus: 'Package status',
            filterShippedFrom: 'Shipped from',
            filterShippedTo: 'Shipped to',
            filterDeliveredFrom: 'Delivered from',
            filterDeliveredTo: 'Delivered to',
            filterOrderNumber: 'Order number',
            filterSan6Package: 'San6 package',
            filterSan6OrderNumber: 'San6 order number',
            filterOrderStatus: 'Order status',
            columnSan6PackageNumber: 'San6 package',
            columnOrderNumber: 'Order number',
            columnOrderDate: 'Order date',
            columnCustomerName: 'Customer',
            columnPayment: 'Payment',
            columnOrderStatus: 'Order status',
            columnSan6OrderNumber: 'San6 order number',
            columnSan6PositionNumber: 'San6 position',
            columnQuantity: 'Quantity',
            columnPackageStatus: 'Package status',
            columnShippedAt: 'Shipping date',
            columnDeliveredAt: 'Delivery date',
            columnTrackingNumber: 'Tracking number',
            columnLatestShippingAt: 'Latest shipping',
            columnLatestDeliveryAt: 'Latest delivery',
            columnSupplierDelivery: 'Supplier delivery',
            columnSupplierComment: 'Supplier comment',
            columnNewDelivery: 'New delivery',
            columnNewDeliveryComment: 'New delivery comment',
            columnUpdatedBy: 'Updated by',
            supplierDeliveryStart: 'Supplier delivery start',
            supplierDeliveryEnd: 'Supplier delivery end',
            supplierDeliveryComment: 'Supplier comment',
            newDeliveryStart: 'New delivery start',
            newDeliveryEnd: 'New delivery end',
            newDeliveryComment: 'New delivery comment',
            trackingHistoryTitle: 'Tracking history',
        },
    },
});

Shopware.Locale.extend('de-DE', {
    'lieferzeiten-management': {
        general: {
            mainMenuItemGeneral: 'Lieferzeiten',
            descriptionTextModule: 'Lieferzeiten und Tracking verwalten',
            title: 'Lieferzeiten',
            filtersTitle: 'Filter',
            filterTracking: 'Sendenummer',
            filterPackageStatus: 'Paket-Status',
            filterShippedFrom: 'Versand ab',
            filterShippedTo: 'Versand bis',
            filterDeliveredFrom: 'Lieferung ab',
            filterDeliveredTo: 'Lieferung bis',
            filterOrderNumber: 'Bestellnummer',
            filterSan6Package: 'San6 Paket',
            filterSan6OrderNumber: 'San6 Auftragsnummer',
            filterOrderStatus: 'Bestellstatus',
            columnSan6PackageNumber: 'San6 Paket',
            columnOrderNumber: 'Bestellnummer',
            columnOrderDate: 'Bestelldatum',
            columnCustomerName: 'Kunde',
            columnPayment: 'Zahlart & Zahlungseingang',
            columnOrderStatus: 'Status',
            columnSan6OrderNumber: 'San6 Auftragsnummer',
            columnSan6PositionNumber: 'San6 Auftragsposition',
            columnQuantity: 'Stückzahl',
            columnPackageStatus: 'Paket-Status',
            columnShippedAt: 'Versand-Datum',
            columnDeliveredAt: 'Liefer-Datum',
            columnTrackingNumber: 'Sendenummer',
            columnLatestShippingAt: 'Spätester Versandzeitpunkt',
            columnLatestDeliveryAt: 'Spätester Lieferzeitpunkt',
            columnSupplierDelivery: 'Liefertermin Lieferant',
            columnSupplierComment: 'Kommentar Lieferant',
            columnNewDelivery: 'Neuer Liefertermin',
            columnNewDeliveryComment: 'Kommentar',
            columnUpdatedBy: 'Änderung durch User',
            supplierDeliveryStart: 'Liefertermin Start',
            supplierDeliveryEnd: 'Liefertermin Ende',
            supplierDeliveryComment: 'Kommentar',
            newDeliveryStart: 'Neuer Liefertermin Start',
            newDeliveryEnd: 'Neuer Liefertermin Ende',
            newDeliveryComment: 'Kommentar',
            trackingHistoryTitle: 'Sendungsverlauf',
        },
    },
});
