import './page/lieferzeiten-management-page';
import './page/lieferzeiten-management-settings-page';
import './page/lieferzeiten-management-stats-page';

Shopware.Module.register('lieferzeiten-management', {
    type: 'plugin',
    name: 'lieferzeiten-management',
    title: 'lieferzeiten-management.general.mainMenuItemGeneral',
    description: 'lieferzeiten-management.general.descriptionTextModule',
    color: '#1a73e8',
    icon: 'regular-clock',
    routes: {
        index: {
            component: 'lieferzeiten-management-page',
            path: 'index',
        },
        stats: {
            component: 'lieferzeiten-management-stats-page',
            path: 'stats',
        },
        settings: {
            component: 'lieferzeiten-management-settings-page',
            path: 'settings',
        },
    },
    navigation: [
        {
            id: 'lieferzeiten-management',
            label: 'lieferzeiten-management.general.mainMenuItemGeneral',
            path: 'lieferzeiten.management.index',
            parent: 'sw-order',
            position: 110,
        },
        {
            id: 'lieferzeiten-management-stats',
            label: 'lieferzeiten-management.stats.navigationLabel',
            path: 'lieferzeiten.management.stats',
            parent: 'sw-order',
            position: 111,
        },
        {
            id: 'lieferzeiten-management-settings',
            label: 'lieferzeiten-management.settings.navigationLabel',
            path: 'lieferzeiten.management.settings',
            parent: 'sw-order',
            position: 112,
        },
    ],
});

Shopware.Locale.extend('en-GB', {
    'lieferzeiten-management': {
        general: {
            mainMenuItemGeneral: 'Delivery times',
            descriptionTextModule: 'Manage delivery times and tracking',
            title: 'Delivery times',
            filtersTitle: 'Filters',
            filterTracking: 'Tracking number',
            filterPackageStatus: 'Package status',
            filterShippedFrom: 'Shipped from',
            filterShippedTo: 'Shipped to',
            filterDeliveredFrom: 'Delivered from',
            filterDeliveredTo: 'Delivered to',
            filterLatestShippingFrom: 'Latest shipping from',
            filterLatestShippingTo: 'Latest shipping to',
            filterLatestDeliveryFrom: 'Latest delivery from',
            filterLatestDeliveryTo: 'Latest delivery to',
            filterOrderNumber: 'Order number',
            filterSan6Package: 'San6 package',
            filterSan6OrderNumber: 'San6 order number',
            filterOrderStatus: 'Order status',
            filterBusinessStatus: 'Business status',
            filterUpdatedBy: 'Updated by',
            filterSupplierDeliveryStart: 'Supplier delivery start',
            filterSupplierDeliveryEnd: 'Supplier delivery end',
            filterNewDeliveryStart: 'New delivery start',
            filterNewDeliveryEnd: 'New delivery end',
            selectionTitle: 'Select area and view',
            selectionAreaLabel: 'Area',
            selectionAreaPlaceholder: 'Select area',
            selectionViewLabel: 'View',
            selectionViewPlaceholder: 'Select view',
            areaFirstMedical: 'First Medical',
            areaECommerce: 'E-Commerce',
            areaMedicalSolutions: 'Medical Solutions',
            viewAllOrders: 'All orders',
            viewOpenOrders: 'Open orders',
            kpiTitle: 'Overview',
            kpiOpenOrders: 'Open orders total',
            kpiOverdueShipping: 'Overdue shipping',
            kpiOverdueDelivery: 'Overdue delivery',
            validationRangeRequired: '{label}: start and end dates are required.',
            validationRangeOrder: 'The start date must be before the end date.',
            validationRangeLength: '{label} must be between {min} and {max} days.',
            saveSupplierDeliverySuccess: 'Supplier delivery saved (KW {startWeek}-{endWeek}).',
            saveNewDeliverySuccess: 'New delivery saved (KW {startWeek}-{endWeek}).',
            columnActions: 'Actions',
            actionRequestAdditionalDelivery: 'Additional delivery request',
            taskCreateSuccess: 'Task created and requester notified.',
            taskCreateError: 'Task could not be created.',
            columnSan6PackageNumber: 'San6 package',
            columnOrderNumber: 'Order number',
            columnOrderDate: 'Order date',
            columnCustomerName: 'Customer',
            columnAdditionalCustomerNames: 'Additional names',
            columnPayment: 'Payment',
            columnOrderStatus: 'Order status',
            columnBusinessStatus: 'Business status',
            columnSan6OrderNumber: 'San6 order number',
            columnSan6PositionNumber: 'San6 position',
            columnQuantity: 'Quantity',
            columnPackageStatus: 'Package status',
            columnShippedAt: 'Shipping date',
            columnDeliveredAt: 'Delivery date',
            columnTrackingNumber: 'Tracking number',
            columnLatestShippingAt: 'Latest shipping',
            columnLatestDeliveryAt: 'Latest delivery',
            columnSupplierDelivery: 'Supplier delivery',
            columnSupplierComment: 'Supplier comment',
            columnNewDelivery: 'New delivery',
            columnNewDeliveryComment: 'New delivery comment',
            columnUpdatedBy: 'Updated by',
            updateLabelNewDelivery: 'New delivery',
            updateLabelSupplierDelivery: 'Supplier delivery',
            supplierDeliveryStart: 'Supplier delivery start',
            supplierDeliveryEnd: 'Supplier delivery end',
            supplierDeliveryComment: 'Supplier comment',
            newDeliveryStart: 'New delivery start',
            newDeliveryEnd: 'New delivery end',
            newDeliveryComment: 'New delivery comment',
            trackingInternalShipping: 'Shipped by First Medical',
            trackingHistoryTitle: 'Tracking history',
        },
        settings: {
            title: 'Delivery time settings',
            navigationLabel: 'Delivery time settings',
            mappingTitle: 'Sales channel mapping',
            addMapping: 'Add mapping',
            emptyState: 'No sales channel mappings found.',
            salesChannelLabel: 'Sales channel',
            salesChannelPlaceholder: 'Select sales channel',
            areaLabel: 'Area',
            areaPlaceholder: 'Select area',
            latestShippingOffsetLabel: 'Latest shipping offset (days)',
            latestShippingOffsetPlaceholder: 'Enter days',
            latestDeliveryOffsetLabel: 'Latest delivery offset (days)',
            latestDeliveryOffsetPlaceholder: 'Enter days',
            cutoffTimeLabel: 'Cutoff time',
            cutoffTimePlaceholder: 'HH:MM',
            taskAssignmentTitle: 'Task assignment rules',
            addTaskAssignment: 'Add task assignment',
            taskAssignmentEmptyState: 'No task assignments found.',
            taskAssignmentSalesChannelLabel: 'Sales channel',
            taskAssignmentSalesChannelPlaceholder: 'Select sales channel (optional)',
            taskAssignmentAreaLabel: 'Area',
            taskAssignmentAreaPlaceholder: 'Select area (optional)',
            taskAssignmentTypeLabel: 'Task type',
            taskAssignmentTypePlaceholder: 'Select task type',
            taskAssignmentUserLabel: 'Assigned user',
            taskAssignmentUserPlaceholder: 'Select user',
            taskAssignmentSaveSuccess: 'Task assignment saved.',
            taskAssignmentSaveError: 'Task assignment could not be saved.',
            taskAssignmentDeleteSuccess: 'Task assignment deleted.',
            taskAssignmentDeleteError: 'Task assignment could not be deleted.',
            taskTypeShippingOverdue: 'Overdue shipping',
            taskTypeAdditionalDelivery: 'Additional delivery request',
            saveSuccess: 'Mapping saved.',
            saveError: 'Mapping could not be saved.',
            deleteSuccess: 'Mapping deleted.',
            deleteError: 'Mapping could not be deleted.',
            notificationTitle: 'Notification settings',
            notificationAdd: 'Add notification',
            notificationEmptyState: 'No notification settings found.',
            notificationTypeLabel: 'Notification type',
            notificationTypePlaceholder: 'Select a notification type',
            notificationEnabledLabel: 'Enabled',
            notificationSaveSuccess: 'Notification setting saved.',
            notificationSaveError: 'Notification setting could not be saved.',
            notificationDeleteSuccess: 'Notification setting deleted.',
            notificationDeleteError: 'Notification setting could not be deleted.',
            notificationOrderCreated: 'Order created',
            notificationTrackingAvailable: 'Tracking available',
            notificationDeliveryDateChanged: 'Delivery date changed',
        },
        stats: {
            title: 'Delivery times statistics',
            description: 'Overview of lead times, delays, and volume.',
            navigationLabel: 'Delivery time stats',
            kpiTitle: 'KPIs',
            kpiAverageLeadTime: 'Average lead time',
            kpiAverageLeadTimeValue: '{count} days',
            kpiOverdueRate: 'Overdue rate',
            kpiOverdueRateValue: '{count} %',
            kpiVolume: 'Volume',
            kpiVolumeValue: '{count} packages',
            tableTitle: 'Detailed metrics',
            columnMetric: 'Metric',
            columnValue: 'Value',
        },
    },
});

Shopware.Locale.extend('de-DE', {
    'lieferzeiten-management': {
        general: {
            mainMenuItemGeneral: 'Lieferzeiten',
            descriptionTextModule: 'Lieferzeiten und Tracking verwalten',
            title: 'Lieferzeiten',
            filtersTitle: 'Filter',
            filterTracking: 'Sendenummer',
            filterPackageStatus: 'Paket-Status',
            filterShippedFrom: 'Versand ab',
            filterShippedTo: 'Versand bis',
            filterDeliveredFrom: 'Lieferung ab',
            filterDeliveredTo: 'Lieferung bis',
            filterLatestShippingFrom: 'Spätester Versand ab',
            filterLatestShippingTo: 'Spätester Versand bis',
            filterLatestDeliveryFrom: 'Späteste Lieferung ab',
            filterLatestDeliveryTo: 'Späteste Lieferung bis',
            filterOrderNumber: 'Bestellnummer',
            filterSan6Package: 'San6 Paket',
            filterSan6OrderNumber: 'San6 Auftragsnummer',
            filterOrderStatus: 'Bestellstatus',
            filterBusinessStatus: 'Status (fachlich)',
            filterUpdatedBy: 'Geändert durch',
            filterSupplierDeliveryStart: 'Liefertermin Start',
            filterSupplierDeliveryEnd: 'Liefertermin Ende',
            filterNewDeliveryStart: 'Neuer Liefertermin Start',
            filterNewDeliveryEnd: 'Neuer Liefertermin Ende',
            selectionTitle: 'Bereich und Ansicht auswählen',
            selectionAreaLabel: 'Bereich',
            selectionAreaPlaceholder: 'Bereich auswählen',
            selectionViewLabel: 'Ansicht',
            selectionViewPlaceholder: 'Ansicht auswählen',
            areaFirstMedical: 'First Medical',
            areaECommerce: 'E-Commerce',
            areaMedicalSolutions: 'Medical Solutions',
            viewAllOrders: 'Alle Bestellungen',
            viewOpenOrders: 'Offene Bestellungen',
            kpiTitle: 'Übersicht',
            kpiOpenOrders: 'Offene Bestellungen gesamt',
            kpiOverdueShipping: 'Versand überfällig',
            kpiOverdueDelivery: 'Lieferung überfällig',
            validationRangeRequired: '{label}: Start- und Enddatum sind erforderlich.',
            validationRangeOrder: 'Das Startdatum muss vor dem Enddatum liegen.',
            validationRangeLength: '{label} muss zwischen {min} und {max} Tagen liegen.',
            saveSupplierDeliverySuccess: 'Liefertermin Lieferant gespeichert (KW {startWeek}-{endWeek}).',
            saveNewDeliverySuccess: 'Neuer Liefertermin gespeichert (KW {startWeek}-{endWeek}).',
            columnActions: 'Aktionen',
            actionRequestAdditionalDelivery: 'Zusätzliche Liefertermin-Anfrage',
            taskCreateSuccess: 'Aufgabe erstellt und Anfragesteller benachrichtigt.',
            taskCreateError: 'Aufgabe konnte nicht erstellt werden.',
            columnSan6PackageNumber: 'San6 Paket',
            columnOrderNumber: 'Bestellnummer',
            columnOrderDate: 'Bestelldatum',
            columnCustomerName: 'Kunde',
            columnAdditionalCustomerNames: 'Weitere Namen',
            columnPayment: 'Zahlart & Zahlungseingang',
            columnOrderStatus: 'Status',
            columnBusinessStatus: 'Statut métier',
            columnSan6OrderNumber: 'San6 Auftragsnummer',
            columnSan6PositionNumber: 'San6 Auftragsposition',
            columnQuantity: 'Stückzahl',
            columnPackageStatus: 'Paket-Status',
            columnShippedAt: 'Versand-Datum',
            columnDeliveredAt: 'Liefer-Datum',
            columnTrackingNumber: 'Sendenummer',
            columnLatestShippingAt: 'Spätester Versandzeitpunkt',
            columnLatestDeliveryAt: 'Spätester Lieferzeitpunkt',
            columnSupplierDelivery: 'Liefertermin Lieferant',
            columnSupplierComment: 'Kommentar Lieferant',
            columnNewDelivery: 'Neuer Liefertermin',
            columnNewDeliveryComment: 'Kommentar',
            columnUpdatedBy: 'Änderung durch User',
            updateLabelNewDelivery: 'Neuer Liefertermin',
            updateLabelSupplierDelivery: 'Liefertermin Lieferant',
            supplierDeliveryStart: 'Liefertermin Start',
            supplierDeliveryEnd: 'Liefertermin Ende',
            supplierDeliveryComment: 'Kommentar',
            newDeliveryStart: 'Neuer Liefertermin Start',
            newDeliveryEnd: 'Neuer Liefertermin Ende',
            newDeliveryComment: 'Kommentar',
            trackingInternalShipping: 'Versand durch First Medical',
            trackingHistoryTitle: 'Sendungsverlauf',
        },
        settings: {
            title: 'Lieferzeiten Einstellungen',
            navigationLabel: 'Lieferzeiten Einstellungen',
            mappingTitle: 'Sales-Channel-Zuordnung',
            addMapping: 'Zuordnung hinzufügen',
            emptyState: 'Keine Sales-Channel-Zuordnungen gefunden.',
            salesChannelLabel: 'Sales Channel',
            salesChannelPlaceholder: 'Sales Channel auswählen',
            areaLabel: 'Bereich',
            areaPlaceholder: 'Bereich auswählen',
            latestShippingOffsetLabel: 'Spätester Versand (Tage)',
            latestShippingOffsetPlaceholder: 'Tage eingeben',
            latestDeliveryOffsetLabel: 'Späteste Lieferung (Tage)',
            latestDeliveryOffsetPlaceholder: 'Tage eingeben',
            cutoffTimeLabel: 'Stichtagszeit',
            cutoffTimePlaceholder: 'HH:MM',
            taskAssignmentTitle: 'Aufgaben-Zuordnung',
            addTaskAssignment: 'Aufgaben-Zuordnung hinzufügen',
            taskAssignmentEmptyState: 'Keine Aufgaben-Zuordnungen gefunden.',
            taskAssignmentSalesChannelLabel: 'Sales Channel',
            taskAssignmentSalesChannelPlaceholder: 'Sales Channel auswählen (optional)',
            taskAssignmentAreaLabel: 'Bereich',
            taskAssignmentAreaPlaceholder: 'Bereich auswählen (optional)',
            taskAssignmentTypeLabel: 'Aufgabentyp',
            taskAssignmentTypePlaceholder: 'Aufgabentyp auswählen',
            taskAssignmentUserLabel: 'Zugewiesener Benutzer',
            taskAssignmentUserPlaceholder: 'Benutzer auswählen',
            taskAssignmentSaveSuccess: 'Aufgaben-Zuordnung gespeichert.',
            taskAssignmentSaveError: 'Aufgaben-Zuordnung konnte nicht gespeichert werden.',
            taskAssignmentDeleteSuccess: 'Aufgaben-Zuordnung gelöscht.',
            taskAssignmentDeleteError: 'Aufgaben-Zuordnung konnte nicht gelöscht werden.',
            taskTypeShippingOverdue: 'Versand überfällig',
            taskTypeAdditionalDelivery: 'Zusätzliche Liefertermin-Anfrage',
            saveSuccess: 'Zuordnung gespeichert.',
            saveError: 'Zuordnung konnte nicht gespeichert werden.',
            deleteSuccess: 'Zuordnung gelöscht.',
            deleteError: 'Zuordnung konnte nicht gelöscht werden.',
            notificationTitle: 'Benachrichtigungseinstellungen',
            notificationAdd: 'Benachrichtigung hinzufügen',
            notificationEmptyState: 'Keine Benachrichtigungseinstellungen gefunden.',
            notificationTypeLabel: 'Benachrichtigungstyp',
            notificationTypePlaceholder: 'Benachrichtigungstyp auswählen',
            notificationEnabledLabel: 'Aktiv',
            notificationSaveSuccess: 'Benachrichtigungseinstellung gespeichert.',
            notificationSaveError: 'Benachrichtigungseinstellung konnte nicht gespeichert werden.',
            notificationDeleteSuccess: 'Benachrichtigungseinstellung gelöscht.',
            notificationDeleteError: 'Benachrichtigungseinstellung konnte nicht gelöscht werden.',
            notificationOrderCreated: 'Bestellung erstellt',
            notificationTrackingAvailable: 'Tracking verfügbar',
            notificationDeliveryDateChanged: 'Liefertermin geändert',
        },
        stats: {
            title: 'Lieferzeiten-Statistiken',
            description: 'Übersicht zu Durchlaufzeiten, Verzögerungen und Volumen.',
            navigationLabel: 'Lieferzeiten-Statistiken',
            kpiTitle: 'KPIs',
            kpiAverageLeadTime: 'Durchschnittliche Lieferzeit',
            kpiAverageLeadTimeValue: '{count} Tage',
            kpiOverdueRate: 'Überfälligkeitsquote',
            kpiOverdueRateValue: '{count} %',
            kpiVolume: 'Volumen',
            kpiVolumeValue: '{count} Pakete',
            tableTitle: 'Detailwerte',
            columnMetric: 'Kennzahl',
            columnValue: 'Wert',
        },
    },
});
